server:
  port: 8088

spring:
  application:
    name: ai-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  instance:
    prefer-ip-address: true # This tells Eureka to share the IP, not the Laptop name
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: MySuperSecretJwtKeyForGraduationProject1234
# Your custom Python setting at the ROOT level
python:
  ai:
    url: https://loyce-unlamentable-nonpleadingly.ngrok-free.dev
