server:
  port: 8082

spring:
  application:
    name: notification-service
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: af93c7d979b3ea
    password: 67d7fd8f3cca78
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/